### ISSUE TITLE
ISSUE:ユーザー関連

### ISSUE THREAD

**Issue by 42rakko** [ilovenoah/ft_transcendence#26]
重複するemailアドレスで登録できてしまう
　→重複チェックして同一emailは登録できないようにしてください

editの方で、
重複idで登録しようとしたときにアラート（説明文）がないので、何が起きてるのかわからない
　→ユーザーフレンドリーにしてください

**Comment by mmaekawa** [comment]
> 重複するemailアドレスで登録できてしまう 　→重複チェックして同一emailは登録できないようにしてください
> 
済
