### ISSUE TITLE
ISSUE:ユーザーがdispay nameを登録できるようにする

### ISSUE THREAD

**Issue by 42rakko** [ilovenoah/ft_transcendence#33]
6/15の本科サバのトラセンMTGで判明しました
display nameが必要っぽい

login nameとdisplay nameを分ける
login name同士は重複不可
display name同士は重複不可
login nameとdisplay nameは重複可能

login nameは変更の必要なし

sing up後、初めてのloginでdisplay nameを登録させてください

**Comment by mmaekawa** [comment]
> 6/15の本科サバのトラセンMTGで判明しました display nameが必要っぽい
> 
> login nameとdisplay nameを分ける login name同士は重複不可 display name同士は重複不可 login nameとdisplay nameは重複可能
> 
> login nameは変更の必要なし
> 
> sing up後、初めてのloginでdisplay nameを登録させてください

```
Users can update their information.
```
とのことだったので、edit profileでlogin nameを編集できるようにしていますが、編集できなくて良いと言うことですか？

**Comment by 42rakko** [comment]
loginnameは変更できなくていいです
