### ISSUE TITLE
issue:トーナメントのゲーム画面で、playerのdisplaynameが正しく表示されない

### ISSUE THREAD

**Issue by 42rakko** [ilovenoah/ft_transcendence#74]
おねがいします

**Comment by mmaekawa** [comment]
どんな感じで変ですか？

**Comment by 42rakko** [comment]
正しい表現かわかりませんが、
player1側の画面で、player2のdisplaynameが表示されていません

**Comment by ilovenoah** [comment]
ぼくもplayer1側だけplayer2のdisplaynameが表示されていないです
player2側はどちらもdisplaynameが表示されています
