### ISSUE TITLE
 Both players will use the same keyboard?

### ISSUE THREAD

**Issue by kohshi54** [ilovenoah/ft_transcendence#79]
> Therefore, users must have the ability to participate in a live Pong game against
another player directly on the website. Both players will use the same keyboard.
The Remote players module can enhance this functionality with remote player

Both players will use the same keyboard?

**Comment by 42rakko** [comment]
The Remote players module can enhance this functionality with remote players.
とあり、
Major module: Remote players
It is possible to have two distant players. Each player is located on a separated
computer, accessing the same website and playing the same Pong game.
となっているので、この項目は従わなくていいと思っていますが
一応、player1の画面では w-s a-dで player2のパドルが動かせるようになっています
