### ISSUE TITLE
The aliases will be reset when a new tournament begins. 

### ISSUE THREAD

**Issue by kohshi54** [ilovenoah/ft_transcendence#80]
> A registration system is required: at the start of a tournament, each player
must input their alias name. The aliases will be reset when a new tournament
begins. However, this requirement can be modified using the Standard User
Management module.

User Management moduleでディスプレイ名設定してるから大丈夫？

**Comment by 42rakko** [comment]
User Management moduleをやってあるので、ここも従わなくて大丈夫だと思います
