### ISSUE TITLE
[issue/fixed]:security concerns?

### ISSUE THREAD

**Issue by kohshi54** [ilovenoah/ft_transcendence#82]
>Regardless of whether you choose to implement the JWT Security module with
2FA, it’s crucial to prioritize the security of your website. For instance, if you opt
to create an API, ensure your routes are protected. Remember, even if you decide
not to use JWT tokens, securing the site remains essential

よく分からないのですが、どこか怪しいところあったりしますか？

**Comment by 42rakko** [comment]
うーん
これはやってないかも
検証します

**Comment by 42rakko** [comment]
websocketを接続しようとしたとき、userがログインしてなかったら、切断するようにした
